#!/usr/bin/env python3
"""Writes 003_seed.sql. Hand-writing 200+ menu rows is how typos get in."""
import random, io

MENS   = list("ABCDKLMNPQRT")            # men's hostel blocks at VIT Vellore
LADIES = list("ABCDEFGHJS")              # ladies' hostel blocks

# name, base price in paise, cooking minutes, cut-off
# Every item here has a picture in client/public/items. Items without one were
# taken out rather than shown as a coloured tile next to photographed ones —
# a half-illustrated menu looks worse than a smaller one.
CATALOGUE = [
    ("Maggi", 4000, 6, "00:15"), ("Cheese Maggi", 5500, 7, "00:15"),
    ("Egg Maggi", 5500, 7, "00:15"), ("Masala Maggi", 4500, 6, "00:15"),
    
    ("Cheese garlic bread", 7000, 8, "00:00"), ("Veg momos", 7000, 11, "23:45"),
    ("Paneer momos", 8500, 12, "23:45"), ("Veg fried rice", 9000, 14, "23:45"),
    ("Egg fried rice", 9500, 14, "23:45"), ("Paneer fried rice", 11000, 15, "23:45"),
    ("Schezwan fried rice", 9500, 14, "23:45"), ("Veg noodles", 8500, 12, "23:45"),
    ("Egg noodles", 9000, 12, "23:45"), ("Schezwan noodles", 9000, 13, "23:45"),
    ("Plain dosa", 5000, 9, "23:30"), ("Masala dosa", 7000, 11, "23:30"),
    ("Onion uttapam", 6500, 12, "23:30"), ("Idli vada", 4500, 7, "23:30"),
    ("Ghee podi idli", 5500, 8, "23:30"), 
    
    
    ("Veg burger", 7000, 9, "00:00"), 
    ("Pav bhaji", 7500, 12, "23:45"), 
    ("Bread omelette", 4500, 6, "00:00"), ("Boiled eggs", 3000, 4, "00:15"),
    ("Filter coffee", 2500, 3, "00:20"),
    ("Masala chai", 2000, 3, "00:20"),
    ("Green tea", 2000, 3, "00:20"), ("Lemon tea", 2500, 3, "23:55"),
    ("Fresh lime soda", 3500, 3, "00:20"), 
    ("Banana shake", 6500, 5, "00:15"), ("Chocolate shake", 7000, 5, "00:15"),
    ("Oreo shake", 7500, 6, "00:15"),
]

def slug(n):
    return n.lower().replace(" ", "-")

def side(t):
    return "Mens" if t == "mens" else "Ladies"

def sq(t):
    # apostrophes have to be doubled inside a SQL string literal
    return t.replace("'", "''")

CLOSES = ["00:30", "00:30", "00:15", "00:00", "23:45"]
PER_COUNTER = 10

def main():
    random.seed(2026)                     # same file every run
    out = io.StringIO()
    out.write("-- NightIT seed. GENERATED by gen_seed.py — edit that, not this.\n"
              "-- Block letters are VIT Vellore's. Item names, prices, cooking times\n"
              "-- and stock are plausible placeholders for the demo, not published\n"
              "-- mess data.\n\n"
              "TRUNCATE stock, order_items, orders, menu_items, counters, blocks "
              "RESTART IDENTITY CASCADE;\n\n")

    # Both hostels really do have an A block, so the name alone is not unique;
    # the table is keyed on (name, hostel_type) and the counter name carries the
    # hostel for the staff dropdown.
    blocks = ([(f"{c}-Block", "mens") for c in MENS]
              + [(f"{c}-Block", "ladies") for c in LADIES])

    out.write("INSERT INTO blocks (name, hostel_type, opens_at, closes_at) VALUES\n")
    out.write(",\n".join(
        f"  ('{n}','{t}','22:30','{CLOSES[i % len(CLOSES)]}')"
        for i, (n, t) in enumerate(blocks)) + ";\n\n")

    out.write("INSERT INTO counters (block_id, name, avg_service_seconds) VALUES\n")
    out.write(",\n".join(
        f"  ({i+1},'{side(t)} {n} night counter',{70 + (i * 7) % 55})"
        for i, (n, t) in enumerate(blocks)) + ";\n\n")

    rows = []
    for ci in range(1, len(blocks) + 1):
        # every counter carries a different slice of the catalogue, so no two
        # blocks look alike
        picks = random.sample(CATALOGUE, PER_COUNTER)
        for name, price, mins, cut in picks:
            # whole rupees only — a half-rupee price shows fine but reads
            # oddly on a bill
            bump = random.choice([-500, 0, 0, 500, 1000])
            rows.append(f"  ({ci},'{sq(name)}',{max(2000, price + bump)},{mins},"
                        f"'{cut}','/items/{slug(name)}.jpg')")
    out.write("INSERT INTO menu_items (counter_id, name, price_paise, prep_minutes, "
              "cutoff_at, image_url) VALUES\n" + ",\n".join(rows) + ";\n\n")

    # one item in eleven starts sold out, so the greyed-out state is visible
    out.write("INSERT INTO stock (menu_item_id, remaining)\n"
              "SELECT id, CASE WHEN id % 11 = 0 THEN 0 ELSE 12 + (id % 28) END\n"
              "  FROM menu_items;\n")

    import os
    here = os.path.dirname(os.path.abspath(__file__))
    dest = os.path.join(here, "..", "sql", "003_seed.sql")
    open(dest, "w").write(out.getvalue())
    print(f"{len(blocks)} blocks, {len(rows)} menu rows, "
          f"{len(CATALOGUE)} items in the catalogue")

main()
